#!/usr/bin/env python3
"""Generates res/Lariat.svg and src/layout_lariat.hpp."""

W, H = 50.8, 128.5  # 10 HP

# ---------------------------------------------------------------- layout ----
REC_BTN = (14.0, 16.5)
PLAY_BTN = (36.8, 16.5)
BTN_LED_DY = -6.6
BTN_LABEL_Y = 23.4

SPEED = (25.4, 34.0)
SPEED_LABEL = 42.8

R1 = 53.5   # rec gate, play gate, clock
R2 = 66.5   # reset, eol
C3 = [10.0, 25.4, 40.8]

IO_HDR_Y = 74.5
IN_X, OUT_X = 14.0, 36.8
IO_Y = [81.5, 94.0, 106.5, 119.0]   # voct, gate, cv1, cv2

TITLE = (W / 2, 7.0)

BG = "#23262c"
FG = "#e8e4da"
DIM = "#8b8f99"
RING = "#3c414b"
ACCENT = "#d9a441"

F = {
    'A': [[(0,6),(2,0),(4,6)], [(0.9,3.9),(3.1,3.9)]],
    'C': [[(4,1),(3,0),(1,0),(0,1),(0,5),(1,6),(3,6),(4,5)]],
    'D': [[(0,0),(0,6)], [(0,0),(2.8,0),(4,1.4),(4,4.6),(2.8,6),(0,6)]],
    'E': [[(4,0),(0,0),(0,6),(4,6)], [(0,3),(2.8,3)]],
    'G': [[(4,1),(3,0),(1,0),(0,1),(0,5),(1,6),(3,6),(4,5),(4,3.2),(2.4,3.2)]],
    'I': [[(2,0),(2,6)]],
    'K': [[(0,0),(0,6)], [(4,0),(0,3.2),(4,6)]],
    'L': [[(0,0),(0,6),(4,6)]],
    'N': [[(0,6),(0,0),(4,6),(4,0)]],
    'O': [[(1,0),(3,0),(4,1),(4,5),(3,6),(1,6),(0,5),(0,1),(1,0)]],
    'P': [[(0,6),(0,0),(3,0),(4,0.9),(4,2.3),(3,3.2),(0,3.2)]],
    'Q': [[(1,0),(3,0),(4,1),(4,5),(3,6),(1,6),(0,5),(0,1),(1,0)], [(2.6,4.4),(4.3,6.5)]],
    'R': [[(0,6),(0,0),(3,0),(4,0.9),(4,2.3),(3,3.2),(0,3.2)], [(2,3.2),(4,6)]],
    'S': [[(4,0.9),(3,0),(1,0),(0,0.9),(0,2.1),(1,3),(3,3),(4,3.9),(4,5.1),(3,6),(1,6),(0,5.1)]],
    'T': [[(0,0),(4,0)], [(2,0),(2,6)]],
    'U': [[(0,0),(0,5),(1,6),(3,6),(4,5),(4,0)]],
    'V': [[(0,0),(2,6),(4,0)]],
    'Y': [[(0,0),(2,3),(4,0)], [(2,3),(2,6)]],
    '/': [[(0.4,6.4),(3.6,-0.4)]],
    '1': [[(1,1.2),(2.2,0),(2.2,6)], [(1,6),(3.4,6)]],
    '2': [[(0,1),(1,0),(3,0),(4,1),(4,2),(0,6),(4,6)]],
    ' ': [],
}

def text_paths(x, y, s, h, color, weight=None):
    scale = h / 6.0
    adv = 5.4 * scale
    width = adv * len(s) - 1.4 * scale
    x0 = x - width / 2.0
    sw = weight if weight else max(0.28, h * 0.16)
    out = []
    for i, ch in enumerate(s.upper()):
        gx = x0 + i * adv
        for line in F.get(ch, []):
            pts = " ".join(
                f"{'M' if j == 0 else 'L'} {gx + px * scale:.3f} {y - h / 2.0 + py * scale:.3f}"
                for j, (px, py) in enumerate(line)
            )
            out.append(
                f'<path d="{pts}" fill="none" stroke="{color}" '
                f'stroke-width="{sw:.3f}" stroke-linecap="round" stroke-linejoin="round"/>'
            )
    return "\n".join(out)

def ring(x, y, r, color=RING, sw=0.5):
    return f'<circle cx="{x}" cy="{y}" r="{r}" fill="none" stroke="{color}" stroke-width="{sw}"/>'

svg = []
svg.append(f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}mm" height="{H}mm" viewBox="0 0 {W} {H}">')
svg.append(f'<rect x="0" y="0" width="{W}" height="{H}" fill="{BG}"/>')
svg.append(f'<rect x="0.4" y="0.4" width="{W-0.8}" height="{H-0.8}" fill="none" stroke="#171a1f" stroke-width="0.8"/>')

svg.append(text_paths(*TITLE, "LARIAT", 4.0, ACCENT, weight=0.8))
# lasso glyph: loop with a tail
svg.append(f'<circle cx="8.5" cy="6.6" r="2.6" fill="none" stroke="{ACCENT}" stroke-width="0.55" opacity="0.7"/>')
svg.append(f'<path d="M 10.4 8.4 C 12.5 10.5 9.5 11.5 11.5 13" fill="none" stroke="{ACCENT}" stroke-width="0.55" opacity="0.7"/>')

svg.append(text_paths(REC_BTN[0], BTN_LABEL_Y, "REC", 1.8, DIM))
svg.append(text_paths(PLAY_BTN[0], BTN_LABEL_Y, "PLAY", 1.8, DIM))
svg.append(text_paths(SPEED[0], SPEED_LABEL, "SPEED", 2.1, FG))

for x, label in zip(C3, ["REC", "PLAY", "CLOCK"]):
    svg.append(ring(x, R1, 4.4))
    svg.append(text_paths(x, R1 - 6.4, label, 1.5, DIM))
svg.append(ring(C3[0], R2, 4.4))
svg.append(text_paths(C3[0], R2 - 6.4, "RESET", 1.5, DIM))
svg.append(text_paths(C3[1], R2 - 6.4, "QUANT", 1.5, DIM))
svg.append(ring(C3[2], R2, 4.4, ACCENT))
svg.append(text_paths(C3[2], R2 - 6.4, "EOL", 1.5, FG))

svg.append(text_paths(IN_X, IO_HDR_Y, "IN", 2.1, FG))
svg.append(text_paths(OUT_X, IO_HDR_Y, "OUT", 2.1, FG))
for y, label in zip(IO_Y, ["V/OCT", "GATE", "CV 1", "CV 2"]):
    svg.append(ring(IN_X, y, 4.4))
    svg.append(ring(OUT_X, y, 4.4, ACCENT))
    svg.append(text_paths(25.4, y, label, 1.5, DIM))

svg.append('</svg>')

import os
base = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(base, "res", "Lariat.svg"), "w") as f:
    f.write("\n".join(svg) + "\n")

hpp = f"""// Generated by gen_lariat.py — do not edit by hand.
#pragma once

namespace llayout {{
constexpr float REC_BTN_X = {REC_BTN[0]}f, REC_BTN_Y = {REC_BTN[1]}f;
constexpr float PLAY_BTN_X = {PLAY_BTN[0]}f, PLAY_BTN_Y = {PLAY_BTN[1]}f;
constexpr float BTN_LED_DY = {BTN_LED_DY}f;
constexpr float SPEED_X = {SPEED[0]}f, SPEED_Y = {SPEED[1]}f;
constexpr float R1 = {R1}f, R2 = {R2}f;
constexpr float C3[3] = {{{', '.join(f'{x}f' for x in C3)}}};
constexpr float IN_X = {IN_X}f, OUT_X = {OUT_X}f;
constexpr float IO_Y[4] = {{{', '.join(f'{y}f' for y in IO_Y)}}};
}}
"""
with open(os.path.join(base, "src", "layout_lariat.hpp"), "w") as f:
    f.write(hpp)

print("wrote res/Lariat.svg and src/layout_lariat.hpp")
