#!/usr/bin/env python3
"""Generates res/Maelstrom.svg and src/layout_maelstrom.hpp."""

W, H = 60.96, 128.5  # 12 HP

# ---------------------------------------------------------------- layout ----
YA = 15.0
YA_LABEL = 21.6
LEVEL_X, MIXK_X, MIXCV_X = 10.0, 26.0, 41.0
LED_X, LED_Y = 52.0, 12.0   # temphonic LEDs (2) + clock LED

YB = 33.5
YB_LABEL = 45.4
PITCH_X, ECHO_X = 17.0, 44.0

YC = 56.5
YC_LABEL = 66.4
DEPTH_X, FB_X, FRZ_X = 10.0, 30.5, 51.0

YD = 72.2
YD_LABEL = 73.4
TRIM_X = [10.0, 23.6, 37.2, 50.8]   # depth attn, pitch1 attn, fb attn, echo attn

R1, R2, R3 = 84.0, 98.0, 113.0
JC = [10.0, 23.6, 37.2, 50.8]

TITLE = (W / 2, 7.0)

BG = "#23262c"
FG = "#e8e4da"
DIM = "#8b8f99"
RING = "#3c414b"
ACCENT = "#d9a441"

F = {
    'A': [[(0,6),(2,0),(4,6)], [(0.9,3.9),(3.1,3.9)]],
    'B': [[(0,6),(0,0),(3,0),(4,0.8),(4,2.2),(3,3),(0,3)], [(3,3),(4,3.8),(4,5.2),(3,6),(0,6)]],
    'C': [[(4,1),(3,0),(1,0),(0,1),(0,5),(1,6),(3,6),(4,5)]],
    'D': [[(0,0),(0,6)], [(0,0),(2.8,0),(4,1.4),(4,4.6),(2.8,6),(0,6)]],
    'E': [[(4,0),(0,0),(0,6),(4,6)], [(0,3),(2.8,3)]],
    'F': [[(4,0),(0,0),(0,6)], [(0,3),(2.8,3)]],
    'H': [[(0,0),(0,6)], [(4,0),(4,6)], [(0,3),(4,3)]],
    'I': [[(2,0),(2,6)]],
    'K': [[(0,0),(0,6)], [(4,0),(0,3.2),(4,6)]],
    'L': [[(0,0),(0,6),(4,6)]],
    'M': [[(0,6),(0,0),(2,3.2),(4,0),(4,6)]],
    'N': [[(0,6),(0,0),(4,6),(4,0)]],
    'O': [[(1,0),(3,0),(4,1),(4,5),(3,6),(1,6),(0,5),(0,1),(1,0)]],
    'P': [[(0,6),(0,0),(3,0),(4,0.9),(4,2.3),(3,3.2),(0,3.2)]],
    'R': [[(0,6),(0,0),(3,0),(4,0.9),(4,2.3),(3,3.2),(0,3.2)], [(2,3.2),(4,6)]],
    'S': [[(4,0.9),(3,0),(1,0),(0,0.9),(0,2.1),(1,3),(3,3),(4,3.9),(4,5.1),(3,6),(1,6),(0,5.1)]],
    'T': [[(0,0),(4,0)], [(2,0),(2,6)]],
    'U': [[(0,0),(0,5),(1,6),(3,6),(4,5),(4,0)]],
    'V': [[(0,0),(2,6),(4,0)]],
    'X': [[(0,0),(4,6)], [(4,0),(0,6)]],
    'Z': [[(0,0),(4,0),(0,6),(4,6)]],
    '1': [[(1,1.2),(2.2,0),(2.2,6)], [(1,6),(3.4,6)]],
    '2': [[(0,1),(1,0),(3,0),(4,1),(4,2),(0,6),(4,6)]],
    ' ': [],
}

def text_paths(x, y, s, h, color, weight=None):
    scale = h / 6.0
    adv = 5.4 * scale
    width = adv * len(s) - 1.4 * scale
    x0 = x - width / 2.0
    sw = weight if weight else max(0.28, h * 0.16)
    out = []
    for i, ch in enumerate(s.upper()):
        gx = x0 + i * adv
        for line in F.get(ch, []):
            pts = " ".join(
                f"{'M' if j == 0 else 'L'} {gx + px * scale:.3f} {y - h / 2.0 + py * scale:.3f}"
                for j, (px, py) in enumerate(line)
            )
            out.append(
                f'<path d="{pts}" fill="none" stroke="{color}" '
                f'stroke-width="{sw:.3f}" stroke-linecap="round" stroke-linejoin="round"/>'
            )
    return "\n".join(out)

def ring(x, y, r, color=RING, sw=0.5):
    return f'<circle cx="{x}" cy="{y}" r="{r}" fill="none" stroke="{color}" stroke-width="{sw}"/>'

svg = []
svg.append(f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}mm" height="{H}mm" viewBox="0 0 {W} {H}">')
svg.append(f'<rect x="0" y="0" width="{W}" height="{H}" fill="{BG}"/>')
svg.append(f'<rect x="0.4" y="0.4" width="{W-0.8}" height="{H-0.8}" fill="none" stroke="#171a1f" stroke-width="0.8"/>')

svg.append(text_paths(*TITLE, "MAELSTROM", 3.8, ACCENT, weight=0.8))
# whirlpool spiral
import math
pts = []
for i in range(30):
    a = i * 0.42
    r = 0.32 * math.exp(0.12 * a)
    pts.append((8.0 + r * math.cos(a), 6.6 + r * math.sin(a) * 0.7))
d = "M " + " L ".join(f"{px:.2f} {py:.2f}" for px, py in pts)
svg.append(f'<path d="{d}" fill="none" stroke="{ACCENT}" stroke-width="0.5" opacity="0.7"/>')

svg.append(text_paths(LEVEL_X, YA_LABEL, "LEVEL", 1.6, FG))
svg.append(text_paths(MIXK_X, YA_LABEL, "MIX", 1.8, FG))
svg.append(text_paths(MIXCV_X, YA_LABEL, "MIX CV", 1.5, DIM))
svg.append(ring(MIXCV_X, YA, 4.4))

svg.append(text_paths(PITCH_X, YB_LABEL, "PITCH", 2.3, FG))
svg.append(text_paths(ECHO_X, YB_LABEL, "ECHO", 2.3, FG))

svg.append(text_paths(DEPTH_X, YC_LABEL, "DEPTH", 1.8, FG))
svg.append(text_paths(FB_X, YC_LABEL, "FEEDBACK", 1.8, FG))
svg.append(text_paths(FRZ_X, YC_LABEL, "FREEZE", 1.6, DIM))


JACKS = [
    (JC[0], R1, "DEPTH", 0), (JC[1], R1, "PITCH 1", 0), (JC[2], R1, "PITCH 2", 0), (JC[3], R1, "ECHO", 0),
    (JC[0], R2, "FB CV", 0), (JC[1], R2, "TEMPO", 0), (JC[2], R2, "CLK", 1), (JC[3], R2, "FRZ", 0),
    (JC[0], R3, "IN", 0), (JC[1], R3, "FB IN", 0), (JC[2], R3, "FB OUT", 1), (JC[3], R3, "OUT", 1),
]
for x, y, label, is_out in JACKS:
    svg.append(ring(x, y, 4.4, ACCENT if is_out else RING))
    svg.append(text_paths(x, y - 6.4, label, 1.5, FG if is_out else DIM))

svg.append('</svg>')

import os
base = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(base, "res", "Maelstrom.svg"), "w") as f:
    f.write("\n".join(svg) + "\n")

hpp = f"""// Generated by gen_maelstrom.py — do not edit by hand.
#pragma once

namespace mslayout {{
constexpr float YA = {YA}f;
constexpr float LEVEL_X = {LEVEL_X}f, MIXK_X = {MIXK_X}f, MIXCV_X = {MIXCV_X}f;
constexpr float LED_X = {LED_X}f, LED_Y = {LED_Y}f;
constexpr float YB = {YB}f;
constexpr float PITCH_X = {PITCH_X}f, ECHO_X = {ECHO_X}f;
constexpr float YC = {YC}f;
constexpr float DEPTH_X = {DEPTH_X}f, FB_X = {FB_X}f, FRZ_X = {FRZ_X}f;
constexpr float YD = {YD}f;
constexpr float TRIM_X[4] = {{{', '.join(f'{x}f' for x in TRIM_X)}}};
constexpr float R1 = {R1}f, R2 = {R2}f, R3 = {R3}f;
constexpr float JC[4] = {{{', '.join(f'{x}f' for x in JC)}}};
}}
"""
with open(os.path.join(base, "src", "layout_maelstrom.hpp"), "w") as f:
    f.write(hpp)

print("wrote res/Maelstrom.svg and src/layout_maelstrom.hpp")
