#!/usr/bin/env python3
"""Generates res/Fretwork.svg and src/layout_fretwork.hpp."""

W, H = 40.64, 128.5  # 8 HP

# ---------------------------------------------------------------- layout ----
# note keyboard: 12 buttons, C at the bottom
KEY_X, KEY_BLACK_X = 9.5, 16.0
KEY_LIGHT_DX = 6.4
KEY_Y0, KEY_DY = 62.0, 3.85   # C at bottom, ascending upward

SCALE_X, SCALE_Y = 30.5, 24.0
ROOT_X, ROOT_Y = 30.5, 42.0
OCT_X, OCT_Y = 30.5, 57.5

R1, R2, R3 = 76.0, 90.5, 106.0
C3 = [8.5, 20.3, 32.1]

TITLE = (W / 2, 7.0)

BG = "#23262c"
FG = "#e8e4da"
DIM = "#8b8f99"
RING = "#3c414b"
ACCENT = "#d9a441"

F = {
    'A': [[(0,6),(2,0),(4,6)], [(0.9,3.9),(3.1,3.9)]],
    'C': [[(4,1),(3,0),(1,0),(0,1),(0,5),(1,6),(3,6),(4,5)]],
    'E': [[(4,0),(0,0),(0,6),(4,6)], [(0,3),(2.8,3)]],
    'F': [[(4,0),(0,0),(0,6)], [(0,3),(2.8,3)]],
    'G': [[(4,1),(3,0),(1,0),(0,1),(0,5),(1,6),(3,6),(4,5),(4,3.2),(2.4,3.2)]],
    'I': [[(2,0),(2,6)]],
    'K': [[(0,0),(0,6)], [(4,0),(0,3.2),(4,6)]],
    'L': [[(0,0),(0,6),(4,6)]],
    'N': [[(0,6),(0,0),(4,6),(4,0)]],
    'O': [[(1,0),(3,0),(4,1),(4,5),(3,6),(1,6),(0,5),(0,1),(1,0)]],
    'R': [[(0,6),(0,0),(3,0),(4,0.9),(4,2.3),(3,3.2),(0,3.2)], [(2,3.2),(4,6)]],
    'S': [[(4,0.9),(3,0),(1,0),(0,0.9),(0,2.1),(1,3),(3,3),(4,3.9),(4,5.1),(3,6),(1,6),(0,5.1)]],
    'T': [[(0,0),(4,0)], [(2,0),(2,6)]],
    'U': [[(0,0),(0,5),(1,6),(3,6),(4,5),(4,0)]],
    'W': [[(0,0),(0.9,6),(2,2.4),(3.1,6),(4,0)]],
    ' ': [],
}

def text_paths(x, y, s, h, color, weight=None):
    scale = h / 6.0
    adv = 5.4 * scale
    width = adv * len(s) - 1.4 * scale
    x0 = x - width / 2.0
    sw = weight if weight else max(0.28, h * 0.16)
    out = []
    for i, ch in enumerate(s.upper()):
        gx = x0 + i * adv
        for line in F.get(ch, []):
            pts = " ".join(
                f"{'M' if j == 0 else 'L'} {gx + px * scale:.3f} {y - h / 2.0 + py * scale:.3f}"
                for j, (px, py) in enumerate(line)
            )
            out.append(
                f'<path d="{pts}" fill="none" stroke="{color}" '
                f'stroke-width="{sw:.3f}" stroke-linecap="round" stroke-linejoin="round"/>'
            )
    return "\n".join(out)

def ring(x, y, r, color=RING, sw=0.5):
    return f'<circle cx="{x}" cy="{y}" r="{r}" fill="none" stroke="{color}" stroke-width="{sw}"/>'

svg = []
svg.append(f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}mm" height="{H}mm" viewBox="0 0 {W} {H}">')
svg.append(f'<rect x="0" y="0" width="{W}" height="{H}" fill="{BG}"/>')
svg.append(f'<rect x="0.4" y="0.4" width="{W-0.8}" height="{H-0.8}" fill="none" stroke="#171a1f" stroke-width="0.8"/>')

svg.append(text_paths(*TITLE, "FRETWORK", 3.4, ACCENT, weight=0.7))
# fret glyph
for i, yy in enumerate([10.2, 11.6]):
    svg.append(f'<path d="M 8 {yy} L 32.6 {yy}" stroke="{ACCENT}" stroke-width="0.35" opacity="0.5"/>')
for fx in [12, 17, 23, 28]:
    svg.append(f'<path d="M {fx} 9.6 L {fx} 12.2" stroke="{ACCENT}" stroke-width="0.45" opacity="0.65"/>')

# keyboard backdrop: black-key rows marked
BLACK = [1, 3, 6, 8, 10]
for i in range(12):
    y = KEY_Y0 - i * KEY_DY
    if i in BLACK:
        svg.append(f'<rect x="3.2" y="{y-1.5}" width="2.2" height="3.0" rx="0.5" fill="{RING}"/>')

svg.append(text_paths(SCALE_X, SCALE_Y + 8.6, "SCALE", 1.9, FG))
svg.append(text_paths(ROOT_X, ROOT_Y + 8.6, "ROOT", 1.9, FG))
svg.append(text_paths(OCT_X, OCT_Y + 6.6, "OCT", 1.6, DIM))

JACKS = [
    (C3[0], R1, "SCALE", 0), (C3[1], R1, "ROOT", 0), (C3[2], R1, "TRANS", 0),
    (C3[0], R2, "TRIG", 0), (C3[2], R2, "GATE", 1),
    (C3[0], R3, "IN", 0), (C3[2], R3, "OUT", 1),
]
for x, y, label, is_out in JACKS:
    svg.append(ring(x, y, 4.4, ACCENT if is_out else RING))
    svg.append(text_paths(x, y - 6.4, label, 1.5, FG if is_out else DIM))

svg.append('</svg>')

import os
base = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(base, "res", "Fretwork.svg"), "w") as f:
    f.write("\n".join(svg) + "\n")

hpp = f"""// Generated by gen_fretwork.py — do not edit by hand.
#pragma once

namespace flayout {{
constexpr float KEY_X = {KEY_X}f, KEY_BLACK_X = {KEY_BLACK_X}f;
constexpr float KEY_LIGHT_DX = {KEY_LIGHT_DX}f;
constexpr float KEY_Y0 = {KEY_Y0}f, KEY_DY = {KEY_DY}f;
constexpr float SCALE_X = {SCALE_X}f, SCALE_Y = {SCALE_Y}f;
constexpr float ROOT_X = {ROOT_X}f, ROOT_Y = {ROOT_Y}f;
constexpr float OCT_X = {OCT_X}f, OCT_Y = {OCT_Y}f;
constexpr float R1 = {R1}f, R2 = {R2}f, R3 = {R3}f;
constexpr float C3[3] = {{{', '.join(f'{x}f' for x in C3)}}};
}}
"""
with open(os.path.join(base, "src", "layout_fretwork.hpp"), "w") as f:
    f.write(hpp)

print("wrote res/Fretwork.svg and src/layout_fretwork.hpp")
