#!/usr/bin/env python3
"""Generates res/Remora.svg and src/layout_remora.hpp."""

W, H = 40.64, 128.5  # 8 HP

# ---------------------------------------------------------------- layout ----
LED_X = [12.1, 17.6, 23.1, 28.6]
LED_Y1, LED_Y2 = 11.6, 15.2
BTN_PREV = (5.4, 13.4)
BTN_NEXT = (35.2, 13.4)

KNOB_X = 12.5
CV_X = 29.0
ROW_Y = [27.5, 43.0, 58.5, 74.0]   # ctl 1, 2, 3, dry/wet
ROW_LABEL_DY = -9.8
CV_HDR_Y = 20.4

R1, R2 = 95.5, 114.5
J_X = [12.5, 29.0]

TITLE = (W / 2, 5.6)

BG = "#23262c"
FG = "#e8e4da"
DIM = "#8b8f99"
RING = "#3c414b"
ACCENT = "#d9a441"

F = {
    'A': [[(0,6),(2,0),(4,6)], [(0.9,3.9),(3.1,3.9)]],
    'B': [[(0,0),(0,6)], [(0,0),(3,0),(4,0.9),(4,2.2),(3,3),(0,3)], [(3,3),(4,3.9),(4,5.1),(3,6),(0,6)]],
    'C': [[(4,1),(3,0),(1,0),(0,1),(0,5),(1,6),(3,6),(4,5)]],
    'D': [[(0,0),(0,6)], [(0,0),(2.8,0),(4,1.4),(4,4.6),(2.8,6),(0,6)]],
    'E': [[(4,0),(0,0),(0,6),(4,6)], [(0,3),(2.8,3)]],
    'F': [[(4,0),(0,0),(0,6)], [(0,3),(2.8,3)]],
    'I': [[(2,0),(2,6)]],
    'K': [[(0,0),(0,6)], [(4,0),(0,3.2),(4,6)]],
    'L': [[(0,0),(0,6),(4,6)]],
    'M': [[(0,6),(0,0),(2,3.2),(4,0),(4,6)]],
    'N': [[(0,6),(0,0),(4,6),(4,0)]],
    'O': [[(1,0),(3,0),(4,1),(4,5),(3,6),(1,6),(0,5),(0,1),(1,0)]],
    'R': [[(0,6),(0,0),(3,0),(4,0.9),(4,2.3),(3,3.2),(0,3.2)], [(2,3.2),(4,6)]],
    'T': [[(0,0),(4,0)], [(2,0),(2,6)]],
    'U': [[(0,0),(0,5),(1,6),(3,6),(4,5),(4,0)]],
    'V': [[(0,0),(2,6),(4,0)]],
    'W': [[(0,0),(0.8,6),(2,2.6),(3.2,6),(4,0)]],
    'X': [[(0,0),(4,6)], [(4,0),(0,6)]],
    '/': [[(0.4,6.4),(3.6,-0.4)]],
    '1': [[(1,1.2),(2.2,0),(2.2,6)], [(1,6),(3.4,6)]],
    '2': [[(0,1),(1,0),(3,0),(4,1),(4,2),(0,6),(4,6)]],
    '3': [[(0,0.8),(1,0),(3,0),(4,1),(4,2),(3,3),(1.6,3)], [(3,3),(4,4),(4,5),(3,6),(1,6),(0,5.2)]],
    ' ': [],
}

def text_paths(x, y, s, h, color, weight=None):
    scale = h / 6.0
    adv = 5.4 * scale
    width = adv * len(s) - 1.4 * scale
    x0 = x - width / 2.0
    sw = weight if weight else max(0.28, h * 0.16)
    out = []
    for i, ch in enumerate(s.upper()):
        gx = x0 + i * adv
        for line in F.get(ch, []):
            pts = " ".join(
                f"{'M' if j == 0 else 'L'} {gx + px * scale:.3f} {y - h / 2.0 + py * scale:.3f}"
                for j, (px, py) in enumerate(line)
            )
            out.append(
                f'<path d="{pts}" fill="none" stroke="{color}" '
                f'stroke-width="{sw:.3f}" stroke-linecap="round" stroke-linejoin="round"/>'
            )
    return "\n".join(out)

def ring(x, y, r, color=RING, sw=0.5):
    return f'<circle cx="{x}" cy="{y}" r="{r}" fill="none" stroke="{color}" stroke-width="{sw}"/>'

svg = []
svg.append(f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}mm" height="{H}mm" viewBox="0 0 {W} {H}">')
svg.append(f'<rect x="0" y="0" width="{W}" height="{H}" fill="{BG}"/>')
svg.append(f'<rect x="0.4" y="0.4" width="{W-0.8}" height="{H-0.8}" fill="none" stroke="#171a1f" stroke-width="0.8"/>')

svg.append(text_paths(*TITLE, "REMORA", 3.8, ACCENT, weight=0.8))

# prev/next arrows beside the LED matrix
svg.append(f'<path d="M {BTN_PREV[0]-1.2} {BTN_PREV[1]+4.6} L {BTN_PREV[0]+1.2} {BTN_PREV[1]+3.4} L {BTN_PREV[0]+1.2} {BTN_PREV[1]+5.8} Z" fill="{DIM}"/>')
svg.append(f'<path d="M {BTN_NEXT[0]+1.2} {BTN_NEXT[1]+4.6} L {BTN_NEXT[0]-1.2} {BTN_NEXT[1]+3.4} L {BTN_NEXT[0]-1.2} {BTN_NEXT[1]+5.8} Z" fill="{DIM}"/>')

# knob rows: 1 / 2 / 3 / D-W with CV jacks
for y, label in zip(ROW_Y, ["1", "2", "3", "D/W"]):
    svg.append(text_paths(CV_X, y + 6.4, label, 1.6, FG))
    svg.append(ring(CV_X, y, 4.4))
svg.append(text_paths(CV_X, CV_HDR_Y, "CV", 1.5, DIM))

for x, label in zip(J_X, ["IN L", "IN R"]):
    svg.append(ring(x, R1, 4.4))
    svg.append(text_paths(x, R1 - 6.4, label, 1.5, DIM))
for x, label in zip(J_X, ["OUT L", "OUT R"]):
    svg.append(ring(x, R2, 4.4, ACCENT))
    svg.append(text_paths(x, R2 - 6.4, label, 1.5, FG))

svg.append('</svg>')

import os
base = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(base, "res", "Remora.svg"), "w") as f:
    f.write("\n".join(svg) + "\n")

hpp = f"""// Generated by gen_remora.py — do not edit by hand.
#pragma once

namespace rmlayout {{
constexpr float LED_X[4] = {{{', '.join(f'{x}f' for x in LED_X)}}};
constexpr float LED_Y1 = {LED_Y1}f, LED_Y2 = {LED_Y2}f;
constexpr float BTN_PREV_X = {BTN_PREV[0]}f, BTN_PREV_Y = {BTN_PREV[1]}f;
constexpr float BTN_NEXT_X = {BTN_NEXT[0]}f, BTN_NEXT_Y = {BTN_NEXT[1]}f;
constexpr float KNOB_X = {KNOB_X}f, CV_X = {CV_X}f;
constexpr float ROW_Y[4] = {{{', '.join(f'{y}f' for y in ROW_Y)}}};
constexpr float R1 = {R1}f, R2 = {R2}f;
constexpr float J_X[2] = {{{', '.join(f'{x}f' for x in J_X)}}};
}}
"""
with open(os.path.join(base, "src", "layout_remora.hpp"), "w") as f:
    f.write(hpp)

print("wrote res/Remora.svg and src/layout_remora.hpp")
