#!/usr/bin/env python3
"""Generates res/Bitrot.svg and src/layout_bitrot.hpp."""

W, H = 71.12, 128.5  # 14 HP

# ---------------------------------------------------------------- layout ----
TIME_KNOB = (16.0, 25.0)
TOP_BTNS = [(38.0, "CLOCK"), (50.5, "MODE"), (63.0, "FREEZE")]
TOP_BTN_Y = 16.0
TOP_LED_Y = 10.3
TOP_LABEL_Y = 22.5

K2_Y = 44.0
K2_LABEL_Y = 52.8
K2 = [(16.0, "RPTS"), (35.0, "BEND"), (49.5, "BREAK"), (64.0, "CRPT")]

MIX_KNOB = (16.0, 64.0)
MIX_LABEL_Y = 72.8
EN_BTN_Y = 62.5
EN_BTNS = [35.0, 49.5, 64.0]      # bend, break, corrupt enable/cycle
EN_LED_DX = -6.6

J = [10.0, 23.3, 36.6, 49.9, 63.2]
R1, R2, R3 = 82.0, 95.0, 108.0

TITLE = (W / 2, 7.0)

BG = "#23262c"
FG = "#e8e4da"
DIM = "#8b8f99"
RING = "#3c414b"
ACCENT = "#d9a441"

F = {
    'A': [[(0,6),(2,0),(4,6)], [(0.9,3.9),(3.1,3.9)]],
    'B': [[(0,6),(0,0),(3,0),(4,0.8),(4,2.2),(3,3),(0,3)], [(3,3),(4,3.8),(4,5.2),(3,6),(0,6)]],
    'C': [[(4,1),(3,0),(1,0),(0,1),(0,5),(1,6),(3,6),(4,5)]],
    'D': [[(0,0),(0,6)], [(0,0),(2.8,0),(4,1.4),(4,4.6),(2.8,6),(0,6)]],
    'E': [[(4,0),(0,0),(0,6),(4,6)], [(0,3),(2.8,3)]],
    'F': [[(4,0),(0,0),(0,6)], [(0,3),(2.8,3)]],
    'G': [[(4,1),(3,0),(1,0),(0,1),(0,5),(1,6),(3,6),(4,5),(4,3.2),(2.4,3.2)]],
    'H': [[(0,0),(0,6)], [(4,0),(4,6)], [(0,3),(4,3)]],
    'I': [[(2,0),(2,6)]],
    'K': [[(0,0),(0,6)], [(4,0),(0,3.2),(4,6)]],
    'L': [[(0,0),(0,6),(4,6)]],
    'M': [[(0,6),(0,0),(2,3.2),(4,0),(4,6)]],
    'N': [[(0,6),(0,0),(4,6),(4,0)]],
    'O': [[(1,0),(3,0),(4,1),(4,5),(3,6),(1,6),(0,5),(0,1),(1,0)]],
    'P': [[(0,6),(0,0),(3,0),(4,0.9),(4,2.3),(3,3.2),(0,3.2)]],
    'R': [[(0,6),(0,0),(3,0),(4,0.9),(4,2.3),(3,3.2),(0,3.2)], [(2,3.2),(4,6)]],
    'S': [[(4,0.9),(3,0),(1,0),(0,0.9),(0,2.1),(1,3),(3,3),(4,3.9),(4,5.1),(3,6),(1,6),(0,5.1)]],
    'T': [[(0,0),(4,0)], [(2,0),(2,6)]],
    'U': [[(0,0),(0,5),(1,6),(3,6),(4,5),(4,0)]],
    'V': [[(0,0),(2,6),(4,0)]],
    'W': [[(0,0),(0.9,6),(2,2.4),(3.1,6),(4,0)]],
    'X': [[(0,0),(4,6)], [(4,0),(0,6)]],
    'Y': [[(0,0),(2,3),(4,0)], [(2,3),(2,6)]],
    'Z': [[(0,0),(4,0),(0,6),(4,6)]],
    ' ': [],
}

def text_paths(x, y, s, h, color, weight=None):
    scale = h / 6.0
    adv = 5.4 * scale
    width = adv * len(s) - 1.4 * scale
    x0 = x - width / 2.0
    sw = weight if weight else max(0.28, h * 0.16)
    out = []
    for i, ch in enumerate(s.upper()):
        gx = x0 + i * adv
        for line in F.get(ch, []):
            pts = " ".join(
                f"{'M' if j == 0 else 'L'} {gx + px * scale:.3f} {y - h / 2.0 + py * scale:.3f}"
                for j, (px, py) in enumerate(line)
            )
            out.append(
                f'<path d="{pts}" fill="none" stroke="{color}" '
                f'stroke-width="{sw:.3f}" stroke-linecap="round" stroke-linejoin="round"/>'
            )
    return "\n".join(out)

def ring(x, y, r, color=RING, sw=0.5):
    return f'<circle cx="{x}" cy="{y}" r="{r}" fill="none" stroke="{color}" stroke-width="{sw}"/>'

svg = []
svg.append(f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}mm" height="{H}mm" viewBox="0 0 {W} {H}">')
svg.append(f'<rect x="0" y="0" width="{W}" height="{H}" fill="{BG}"/>')
svg.append(f'<rect x="0.4" y="0.4" width="{W-0.8}" height="{H-0.8}" fill="none" stroke="#171a1f" stroke-width="0.8"/>')

svg.append(text_paths(*TITLE, "BITROT", 4.2, ACCENT, weight=0.85))
# glitchy bars next to the title
for i, (bx, bw_, op) in enumerate([(8.0, 3.0, 0.7), (12.0, 1.2, 0.5), (14.6, 2.0, 0.8), (54.0, 1.5, 0.6), (57.0, 3.2, 0.75), (61.5, 1.0, 0.5)]):
    svg.append(f'<rect x="{bx}" y="{5.2 + (i % 3) * 0.9}" width="{bw_}" height="1.4" fill="{ACCENT}" opacity="{op}"/>')

svg.append(text_paths(TIME_KNOB[0], 35.3, "TIME", 2.3, FG))
for x, label in TOP_BTNS:
    svg.append(text_paths(x, TOP_LABEL_Y, label, 1.6, DIM))
for x, label in K2:
    svg.append(text_paths(x, K2_LABEL_Y, label, 2.1, FG))
svg.append(text_paths(MIX_KNOB[0], MIX_LABEL_Y, "MIX", 2.1, FG))

# jack labels: (col, row, label, is_output)
JACKS = [
    (J[0], R1, "TIME", 0),  (J[1], R1, "BEND", 0),  (J[2], R1, "BREAK", 0), (J[3], R1, "CRPT", 0),  (J[4], R1, "CLOCK", 0),
    (J[0], R2, "RPTS", 0),  (J[1], R2, "GATE", 0),  (J[2], R2, "GATE", 0),  (J[3], R2, "GATE", 0),  (J[4], R2, "FRZ", 0),
    (J[0], R3, "MIX", 0),   (J[1], R3, "IN L", 0),  (J[2], R3, "IN R", 0),  (J[3], R3, "OUT L", 1), (J[4], R3, "OUT R", 1),
]
for x, y, label, is_out in JACKS:
    svg.append(ring(x, y, 4.4, ACCENT if is_out else RING))
    svg.append(text_paths(x, y - 6.4, label, 1.6, FG if is_out else DIM))

svg.append('</svg>')

import os
base = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(base, "res", "Bitrot.svg"), "w") as f:
    f.write("\n".join(svg) + "\n")

hpp = f"""// Generated by gen_bitrot.py — do not edit by hand.
#pragma once

namespace blayout {{
constexpr float TIME_X = {TIME_KNOB[0]}f, TIME_Y = {TIME_KNOB[1]}f;
constexpr float TOP_BTN_X[3] = {{{TOP_BTNS[0][0]}f, {TOP_BTNS[1][0]}f, {TOP_BTNS[2][0]}f}};
constexpr float TOP_BTN_Y = {TOP_BTN_Y}f;
constexpr float TOP_LED_Y = {TOP_LED_Y}f;
constexpr float K2_Y = {K2_Y}f;
constexpr float K2_X[4] = {{{K2[0][0]}f, {K2[1][0]}f, {K2[2][0]}f, {K2[3][0]}f}};
constexpr float MIX_X = {MIX_KNOB[0]}f, MIX_Y = {MIX_KNOB[1]}f;
constexpr float EN_BTN_Y = {EN_BTN_Y}f;
constexpr float EN_BTN_X[3] = {{{EN_BTNS[0]}f, {EN_BTNS[1]}f, {EN_BTNS[2]}f}};
constexpr float EN_LED_DX = {EN_LED_DX}f;
constexpr float J[5] = {{{J[0]}f, {J[1]}f, {J[2]}f, {J[3]}f, {J[4]}f}};
constexpr float R1 = {R1}f, R2 = {R2}f, R3 = {R3}f;
}}
"""
with open(os.path.join(base, "src", "layout_bitrot.hpp"), "w") as f:
    f.write(hpp)

print("wrote res/Bitrot.svg and src/layout_bitrot.hpp")
