#!/usr/bin/env python3
"""Generates res/Stiletto.svg and src/layout_stiletto.hpp."""

W, H = 40.64, 128.5  # 8 HP

# ---------------------------------------------------------------- layout ----
CX = 20.32
LPF_KNOB = (CX, 20.0)
RES_KNOB = (CX, 41.0)
HPF_KNOB = (CX, 62.0)
LINK_SW = (7.0, 21.0)
HPRES_SW = (7.0, 42.0)     # resonance -> high-pass pair
LPRES_SW = (33.6, 42.0)    # resonance -> low-pass pair

XL, XC, XR = 8.0, CX, 32.6
R1, R2, R3, R4 = 84.0, 95.5, 107.0, 118.5

TITLE = (CX, 9.0)

BG = "#23262c"
FG = "#e8e4da"
DIM = "#8b8f99"
RING = "#3c414b"
ACCENT = "#d9a441"

F = {
    'A': [[(0,6),(2,0),(4,6)], [(0.9,3.9),(3.1,3.9)]],
    'B': [[(0,6),(0,0),(3,0),(4,0.8),(4,2.2),(3,3),(0,3)], [(3,3),(4,3.8),(4,5.2),(3,6),(0,6)]],
    'C': [[(4,1),(3,0),(1,0),(0,1),(0,5),(1,6),(3,6),(4,5)]],
    'D': [[(0,0),(0,6)], [(0,0),(2.8,0),(4,1.4),(4,4.6),(2.8,6),(0,6)]],
    'E': [[(4,0),(0,0),(0,6),(4,6)], [(0,3),(2.8,3)]],
    'F': [[(4,0),(0,0),(0,6)], [(0,3),(2.8,3)]],
    'G': [[(4,1),(3,0),(1,0),(0,1),(0,5),(1,6),(3,6),(4,5),(4,3.2),(2.4,3.2)]],
    'H': [[(0,0),(0,6)], [(4,0),(4,6)], [(0,3),(4,3)]],
    'I': [[(2,0),(2,6)]],
    'K': [[(0,0),(0,6)], [(4,0),(0,3.2),(4,6)]],
    'L': [[(0,0),(0,6),(4,6)]],
    'M': [[(0,6),(0,0),(2,3.2),(4,0),(4,6)]],
    'N': [[(0,6),(0,0),(4,6),(4,0)]],
    'O': [[(1,0),(3,0),(4,1),(4,5),(3,6),(1,6),(0,5),(0,1),(1,0)]],
    'P': [[(0,6),(0,0),(3,0),(4,0.9),(4,2.3),(3,3.2),(0,3.2)]],
    'R': [[(0,6),(0,0),(3,0),(4,0.9),(4,2.3),(3,3.2),(0,3.2)], [(2,3.2),(4,6)]],
    'S': [[(4,0.9),(3,0),(1,0),(0,0.9),(0,2.1),(1,3),(3,3),(4,3.9),(4,5.1),(3,6),(1,6),(0,5.1)]],
    'T': [[(0,0),(4,0)], [(2,0),(2,6)]],
    'U': [[(0,0),(0,5),(1,6),(3,6),(4,5),(4,0)]],
    'V': [[(0,0),(2,6),(4,0)]],
    'W': [[(0,0),(0.9,6),(2,2.4),(3.1,6),(4,0)]],
    'X': [[(0,0),(4,6)], [(4,0),(0,6)]],
    'Y': [[(0,0),(2,3),(4,0)], [(2,3),(2,6)]],
    'Z': [[(0,0),(4,0),(0,6),(4,6)]],
    '1': [[(1,1.2),(2.2,0),(2.2,6)], [(1,6),(3.4,6)]],
    '2': [[(0,1),(1,0),(3,0),(4,1),(4,2),(0,6),(4,6)]],
    ' ': [],
}

def text_paths(x, y, s, h, color, weight=None):
    scale = h / 6.0
    adv = 5.4 * scale
    width = adv * len(s) - 1.4 * scale
    x0 = x - width / 2.0
    sw = weight if weight else max(0.28, h * 0.16)
    out = []
    for i, ch in enumerate(s.upper()):
        gx = x0 + i * adv
        for line in F.get(ch, []):
            pts = " ".join(
                f"{'M' if j == 0 else 'L'} {gx + px * scale:.3f} {y - h / 2.0 + py * scale:.3f}"
                for j, (px, py) in enumerate(line)
            )
            out.append(
                f'<path d="{pts}" fill="none" stroke="{color}" '
                f'stroke-width="{sw:.3f}" stroke-linecap="round" stroke-linejoin="round"/>'
            )
    return "\n".join(out)

def ring(x, y, r, color=RING, sw=0.5):
    return f'<circle cx="{x}" cy="{y}" r="{r}" fill="none" stroke="{color}" stroke-width="{sw}"/>'

svg = []
svg.append(f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}mm" height="{H}mm" viewBox="0 0 {W} {H}">')
svg.append(f'<rect x="0" y="0" width="{W}" height="{H}" fill="{BG}"/>')
svg.append(f'<rect x="0.4" y="0.4" width="{W-0.8}" height="{H-0.8}" fill="none" stroke="#171a1f" stroke-width="0.8"/>')

svg.append(text_paths(*TITLE, "STILETTO", 3.4, ACCENT, weight=0.7))
# small dagger blade glyph under the title
svg.append(f'<path d="M {CX-6} 12.6 L {CX+4.5} 12.6 L {CX+6.5} 13.3 L {CX+4.5} 14.0 L {CX-6} 14.0 Z" fill="{ACCENT}" opacity="0.5"/>')
svg.append(f'<path d="M {CX-4.7} 11.2 L {CX-3.5} 15.4" stroke="{ACCENT}" stroke-width="0.9" opacity="0.5"/>')

# knobs
svg.append(text_paths(CX, 30.6, "LPF", 2.3, FG))
svg.append(text_paths(CX, 51.6, "RES", 2.3, FG))
svg.append(text_paths(CX, 72.6, "HPF", 2.3, FG))

# switches
svg.append(text_paths(LINK_SW[0], 14.8, "LINK", 1.6, DIM))
svg.append(text_paths(HPRES_SW[0], 34.8, "RES", 1.6, DIM))
svg.append(text_paths(HPRES_SW[0], 48.4, "HP", 1.6, DIM))
svg.append(text_paths(LPRES_SW[0], 34.8, "RES", 1.6, DIM))
svg.append(text_paths(LPRES_SW[0], 48.4, "LP", 1.6, DIM))

# jacks: (x, y, label, is_output)
JACKS = [
    (XL, R1, "LPF", 0), (XC, R1, "RES", 0), (XR, R1, "HPF", 0),
    (XL, R2, "PAN LP", 0), (XR, R2, "PAN HP", 0),
    (XL, R3, "IN 1", 0), (XR, R3, "IN 2", 0),
    (XL, R4, "OUT 1", 1), (XR, R4, "OUT 2", 1),
]
for x, y, label, is_out in JACKS:
    svg.append(ring(x, y, 4.4, ACCENT if is_out else RING))
    svg.append(text_paths(x, y - 6.3, label, 1.6, FG if is_out else DIM))

svg.append('</svg>')

import os
base = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(base, "res", "Stiletto.svg"), "w") as f:
    f.write("\n".join(svg) + "\n")

hpp = f"""// Generated by gen_stiletto.py — do not edit by hand.
#pragma once

namespace slayout {{
constexpr float LPF_X = {LPF_KNOB[0]}f, LPF_Y = {LPF_KNOB[1]}f;
constexpr float RES_X = {RES_KNOB[0]}f, RES_Y = {RES_KNOB[1]}f;
constexpr float HPF_X = {HPF_KNOB[0]}f, HPF_Y = {HPF_KNOB[1]}f;
constexpr float LINK_X = {LINK_SW[0]}f, LINK_Y = {LINK_SW[1]}f;
constexpr float HPRES_X = {HPRES_SW[0]}f, HPRES_Y = {HPRES_SW[1]}f;
constexpr float LPRES_X = {LPRES_SW[0]}f, LPRES_Y = {LPRES_SW[1]}f;
constexpr float XL = {XL}f, XC = {XC}f, XR = {XR}f;
constexpr float R1 = {R1}f, R2 = {R2}f, R3 = {R3}f, R4 = {R4}f;
}}
"""
with open(os.path.join(base, "src", "layout_stiletto.hpp"), "w") as f:
    f.write(hpp)

print("wrote res/Stiletto.svg and src/layout_stiletto.hpp")
