// Generated by gen_stiletto.py — do not edit by hand.
#pragma once

namespace slayout {
constexpr float LPF_X = 20.32f, LPF_Y = 20.0f;
constexpr float RES_X = 20.32f, RES_Y = 41.0f;
constexpr float HPF_X = 20.32f, HPF_Y = 62.0f;
constexpr float LINK_X = 7.0f, LINK_Y = 21.0f;
constexpr float HPRES_X = 7.0f, HPRES_Y = 42.0f;
constexpr float LPRES_X = 33.6f, LPRES_Y = 42.0f;
constexpr float XL = 8.0f, XC = 20.32f, XR = 32.6f;
constexpr float R1 = 84.0f, R2 = 95.5f, R3 = 107.0f, R4 = 118.5f;
}
