// Generated by gen_ammonite.py — do not edit by hand.
#pragma once

namespace mlayout {
constexpr float C[4] = {11.0f, 30.7f, 50.5f, 70.2f};
constexpr float BTN_Y = 16.0f;
constexpr float BTN_LED_Y = 10.5f;
constexpr float K1_Y = 31.0f;
constexpr float K2_Y = 50.5f;
constexpr float CHROMA_LED_X = 58.2f, CHROMA_LED_Y = 24.6f;
constexpr float R3 = 71.5f, R4 = 83.5f;
constexpr float J5[5] = {9.0f, 25.0f, 41.0f, 57.0f, 73.0f};
constexpr float R5 = 97.5f, R6 = 113.5f;
constexpr float CLK_LED_X = 41.0f, CLK_LED_Y = 110.0f;
}
