// Generated by gen_lariat.py — do not edit by hand.
#pragma once

namespace llayout {
constexpr float REC_BTN_X = 14.0f, REC_BTN_Y = 16.5f;
constexpr float PLAY_BTN_X = 36.8f, PLAY_BTN_Y = 16.5f;
constexpr float BTN_LED_DY = -6.6f;
constexpr float SPEED_X = 25.4f, SPEED_Y = 34.0f;
constexpr float R1 = 53.5f, R2 = 66.5f;
constexpr float C3[3] = {10.0f, 25.4f, 40.8f};
constexpr float IN_X = 14.0f, OUT_X = 36.8f;
constexpr float IO_Y[4] = {81.5f, 94.0f, 106.5f, 119.0f};
}
