// Generated by gen_remora.py — do not edit by hand.
#pragma once

namespace rmlayout {
constexpr float LED_X[4] = {12.1f, 17.6f, 23.1f, 28.6f};
constexpr float LED_Y1 = 11.6f, LED_Y2 = 15.2f;
constexpr float BTN_PREV_X = 5.4f, BTN_PREV_Y = 13.4f;
constexpr float BTN_NEXT_X = 35.2f, BTN_NEXT_Y = 13.4f;
constexpr float KNOB_X = 12.5f, CV_X = 29.0f;
constexpr float ROW_Y[4] = {27.5f, 43.0f, 58.5f, 74.0f};
constexpr float R1 = 95.5f, R2 = 114.5f;
constexpr float J_X[2] = {12.5f, 29.0f};
}
