// Generated by gen_fieldfare.py — do not edit by hand.
#pragma once

namespace fflayout {
constexpr float YA = 16.0f;
constexpr float BTN_X[4] = {13.0f, 42.0f, 71.0f, 100.0f};
constexpr float YB = 38.0f;
constexpr float KNOB_X[4] = {16.0f, 46.0f, 76.0f, 106.0f};
constexpr float YC = 62.0f;
constexpr float SPEED_X = 16.0f;
constexpr float TR_X[4] = {46.0f, 66.0f, 86.0f, 106.0f};
constexpr float R1 = 92.0f, R2 = 113.0f;
constexpr float J6[6] = {11.0f, 31.0f, 51.0f, 71.0f, 91.0f, 111.0f};
}
