// Generated by gen_foxglove.py — do not edit by hand.
#pragma once

namespace fglayout {
constexpr float SW_Y = 13.0f;
constexpr float SW_X[4] = {7.0f, 19.2f, 31.6f, 44.0f};
constexpr float KX1 = 14.0f, KX2 = 36.8f, KY1 = 33.5f, KY2 = 55.5f;
constexpr float CLIP_LED_X = 25.4f, CLIP_LED_Y = 35.0f;
constexpr float OS_TRIM_X = 25.4f, OS_TRIM_Y = 55.5f;
constexpr float TRIM_Y = 79.0f;
constexpr float TRIM_X[4] = {8.5f, 19.8f, 31.0f, 42.3f};
constexpr float R1 = 95.5f, R2 = 114.5f;
constexpr float J_X[4] = {8.5f, 19.8f, 31.0f, 42.3f};
}
