// Generated by gen_chimera.py — do not edit by hand.
#pragma once

namespace clayout {
constexpr float YA = 15.0f, YA_LED_DY = -5.4f;
constexpr float BTN_X[5] = {12.0f, 26.0f, 40.0f, 54.0f, 68.0f};
constexpr float SOS_X = 14.0f;
constexpr float EQ_X[3] = {56.0f, 76.0f, 96.0f};
constexpr float YB = 32.5f;
constexpr float SPEED_X = 16.0f, PITCH_X = 42.0f;
constexpr float GRAIN_X = 66.0f, SLICE_X = 86.0f, CHOP_X = 103.0f;
constexpr float YC = 53.0f;
constexpr float YD = 72.5f;
constexpr float SCATTER_X = 16.0f;
constexpr float SLICE_LIGHT_X0 = 34.0f, SLICE_LIGHT_DX = 6.4f, SLICE_LIGHT_Y = 72.5f;
constexpr float CLK_LIGHT_X = 103.0f, CLK_LIGHT_Y = 72.5f;
constexpr float R1 = 90.0f, R2 = 104.0f, R3 = 118.0f;
constexpr float J6[6] = {10.0f, 28.0f, 46.0f, 64.0f, 82.0f, 100.0f};
}
