// Generated by gen_sirocco.py — do not edit by hand.
#pragma once

namespace wlayout {
constexpr float C[5] = {10.6f, 30.7f, 50.8f, 70.9f, 91.0f};
constexpr float YA = 14.0f, YA_LED = 8.8f;
constexpr float YB = 33.0f;
constexpr float YC = 56.5f;
constexpr float YD = 75.0f;
constexpr float R1 = 90.0f, R2 = 100.5f, R3 = 111.0f, R4 = 121.5f;
}
