// Generated by gen_chimera.py - do not edit by hand.
#pragma once

namespace clayout {
constexpr float YA = 19.0f;
constexpr float BTN_X[5] = {14.0f, 35.0f, 56.0f, 77.0f, 98.0f};
constexpr float SOS_X = 13.0f;
constexpr float EQ_X[3] = {42.0f, 63.0f, 84.0f};
constexpr float CHOP_X = 102.0f;
constexpr float YB = 35.0f;
constexpr float SPEED_X = 14.0f, PITCH_X = 38.0f;
constexpr float GRAIN_X = 62.0f, SLICE_X = 82.0f, SCATTER_X = 101.0f;
constexpr float YC = 55.0f;
constexpr float DISP_X = 6.0f, DISP_Y = 67.0f, DISP_W = 99.76f, DISP_H = 14.0f;
constexpr float R1 = 90.0f, R2 = 104.0f, R3 = 118.0f;
constexpr float J6[6] = {10.0f, 28.0f, 46.0f, 64.0f, 82.0f, 100.0f};
}
