// Generated by gen_catgut.py — do not edit by hand.
#pragma once

namespace glayout {
constexpr float SOLO_X = 13.0f, MID_X = 40.64f, CHORD_X = 68.3f;
constexpr float ROW1 = 19.5f, ROW2 = 38.5f, ROW3 = 57.5f;
constexpr float TIMBRE_SX = 31.0f, TIMBRE_CX = 50.3f, TIMBRE_Y = 57.5f;
constexpr float TIMBRE_LED_DY = -6.2f;
constexpr float J6[6] = {9.0f, 21.8f, 34.6f, 47.4f, 60.2f, 73.0f};
constexpr float R1 = 80.0f, R2 = 94.0f, R3 = 108.0f;
}
