// Generated by gen_tektite.py — do not edit by hand.
#pragma once

namespace tlayout {
constexpr float J8[8] = {7.5f, 18.7f, 29.9f, 41.1f, 52.3f, 63.5f, 74.7f, 85.9f};
constexpr float YA = 14.0f, YA_LED = 8.3f;
constexpr float FLUT_X = 7.5f, FRZ_X = 20.0f, LOOP_X = 32.0f;
constexpr float VARI_X = 45.7f, VARI_Y = 19.0f;
constexpr float FX_X = 59.4f, UNDO_X = 71.4f, HISS_X = 85.9f;
constexpr float YB = 35.0f;
constexpr float ERASE_X = 7.5f, START_X = 21.0f, INERTIA_X = 45.7f;
constexpr float INERTIA_Y = 36.5f, SIZE_X = 70.4f, MIX_X = 85.9f;
constexpr float YC = 52.0f;
constexpr float LVL_X = 7.5f, SKIP_X = 26.0f, SLICE_X = 65.4f;
constexpr float YD = 66.5f;
constexpr float TR_X[4] = {20.5f, 37.0f, 53.5f, 70.0f};
constexpr float R1 = 84.0f, R2 = 99.0f, R3 = 114.0f;
}
