// Generated by gen_murmur.py — do not edit by hand.
#pragma once

namespace ulayout {
constexpr float ELED_Y = 13.0f, ELED_X0 = 14.0f, ELED_DX = 6.2f;
constexpr float MODEL_X = 12.0f, MODEL_Y = 26.0f;
constexpr float FREQ_X = 35.5f, FREQ_Y = 27.0f;
constexpr float DECAY_X = 59.0f, DECAY_Y = 21.5f;
constexpr float LPG_X = 59.0f, LPG_Y = 34.0f;
constexpr float KB_Y = 47.5f;
constexpr float HARM_X = 12.0f, TIMB_X = 35.5f, MORPH_X = 59.0f;
constexpr float ATT_Y = 64.0f, FMATT_X = 12.0f;
constexpr float R1 = 81.0f, R2 = 97.0f;
constexpr float J6[6] = {9.0f, 19.5f, 30.0f, 40.5f, 51.0f, 61.5f};
}
