// Generated by gen_fretwork.py — do not edit by hand.
#pragma once

namespace flayout {
constexpr float KEY_X = 9.5f, KEY_BLACK_X = 16.0f;
constexpr float KEY_LIGHT_DX = 6.4f;
constexpr float KEY_Y0 = 62.0f, KEY_DY = 3.85f;
constexpr float SCALE_X = 30.5f, SCALE_Y = 24.0f;
constexpr float ROOT_X = 30.5f, ROOT_Y = 42.0f;
constexpr float OCT_X = 30.5f, OCT_Y = 57.5f;
constexpr float R1 = 76.0f, R2 = 90.5f, R3 = 106.0f;
constexpr float C3[3] = {8.5f, 20.3f, 32.1f};
}
