// Generated by gen_espalier.py — do not edit by hand.
#pragma once

namespace elayout {
constexpr float J8[8] = {7.5f, 18.7f, 29.9f, 41.1f, 52.3f, 63.5f, 74.7f, 85.9f};
constexpr float YA = 15.0f;
constexpr float YB = 31.5f;
constexpr float GROW_X = 27.0f, ROUTE_X = 46.7f, EVOLVE_X = 66.4f;
constexpr float YM = 47.5f;
constexpr float PAGE_LIGHT_X0 = 26.0f, PAGE_LIGHT_DX = 5.7f, PAGE_LIGHT_Y = 47.5f;
constexpr float SC[4] = {14.5f, 35.3f, 56.1f, 76.9f};
constexpr float SY1 = 64.0f, SY2 = 81.5f;
constexpr float STEP_LIGHT_DX = -7.8f, STEP_LIGHT_DY = -4.5f;
constexpr float STEP_BTN_DX = 7.8f, STEP_BTN_DY = 4.8f;
constexpr float R1 = 99.0f, R2 = 115.5f;
}
