// Generated by gen_osprey.py — do not edit by hand.
#pragma once

namespace oslayout {
constexpr float MODE_SW_X = 10.0f, SW_Y = 13.0f;
constexpr float OCT_SW_X = 25.4f;
constexpr float MONO_SW_X = 40.8f;
constexpr float KX1 = 14.0f, KX2 = 36.8f, KY1 = 33.5f, KY2 = 55.5f;
constexpr float PG_SW_X = 25.4f, PG_SW_Y = 44.0f;
constexpr float PG_LED_X = 25.4f, PG_LED_Y = 50.5f;
constexpr float TRIM_Y = 79.0f;
constexpr float TRIM_X[4] = {8.5f, 19.8f, 31.0f, 42.3f};
constexpr float R1 = 95.5f, R2 = 114.5f;
constexpr float J_X[4] = {8.5f, 19.8f, 31.0f, 42.3f};
}
