// Generated by gen_panel.py — do not edit by hand.
#pragma once

namespace layout {
constexpr float C[4] = {14.5f, 35.3f, 56.1f, 76.9f};
constexpr float BIG_Y = 27.0f;
constexpr float ATTN_Y = 41.5f;
constexpr float CV_Y = 53.5f;
constexpr float DENS_X = 14.5f, DENS_Y = 74.5f;
constexpr float SEED_BTN_X = 35.3f, SEED_BTN_Y = 74.5f;
constexpr float SEED_LED_X = 35.3f, SEED_LED_Y = 68.5f;
constexpr float MIX_X[3] = {56.1f, 69.0f, 81.9f};
constexpr float MIX_KNOB_Y = 69.0f;
constexpr float MIX_LED_Y = 63.4f;
constexpr float ROW2_Y = 87.5f;
constexpr float IO_Y = 113.5f;
constexpr float IN_L_X = 11.5f, IN_R_X = 25.0f;
constexpr float OUT_L_X = 67.5f, OUT_R_X = 81.0f;
constexpr float PEAK_X = 33.8f, PEAK_Y = 121.0f;
constexpr float QUAL_BTN_X = 9.0f, QUAL_BTN_Y = 10.5f;
constexpr float QUAL_LED_X = 15.5f, QUAL_LED_Y = 10.5f;
constexpr float FRZ_BTN_X = 82.4f, FRZ_BTN_Y = 10.5f;
constexpr float FRZ_LED_X = 75.9f, FRZ_LED_Y = 10.5f;
}
