// Generated by gen_haymaker.py — do not edit by hand.
#pragma once

namespace hlayout {
constexpr float PAD_X[3] = {12.0f, 30.0f, 48.0f};
constexpr float PAD_Y[4] = {30.0f, 48.0f, 66.0f, 84.0f};
constexpr float PAD_LIGHT_DX = 6.2f, PAD_LIGHT_DY = -6.2f;
constexpr float KN_Y = 27.0f;
constexpr float KN_X[4] = {70.0f, 84.0f, 98.0f, 112.0f};
constexpr float FX_Y = 46.5f, FX_LED_Y = 40.8f;
constexpr float FX_X[6] = {68.0f, 77.4f, 86.8f, 96.2f, 105.6f, 115.0f};
constexpr float TK_Y = 64.0f;
constexpr float BPM_X = 70.0f, SWING_X = 84.0f, STEPS_X = 98.0f;
constexpr float FADER_X = 114.0f, FADER_Y = 72.0f;
constexpr float RUN_X = 70.0f, REC_X = 84.0f, TR_Y = 84.0f;
constexpr float ST_X0 = 11.0f, ST_DX = 11.6f;
constexpr float ST_Y1 = 103.0f, ST_Y2 = 112.0f, ST_LIGHT_DY = -4.6f;
constexpr float JK_Y1 = 103.5f, JK_Y2 = 117.0f;
constexpr float CLK_X = 102.0f, RST_X = 113.5f;
constexpr float OUTL_X = 102.0f, OUTR_X = 113.5f;
}
