// Generated by gen_bitrot.py — do not edit by hand.
#pragma once

namespace blayout {
constexpr float TIME_X = 16.0f, TIME_Y = 25.0f;
constexpr float TOP_BTN_X[3] = {38.0f, 50.5f, 63.0f};
constexpr float TOP_BTN_Y = 16.0f;
constexpr float TOP_LED_Y = 10.3f;
constexpr float K2_Y = 44.0f;
constexpr float K2_X[4] = {16.0f, 35.0f, 49.5f, 64.0f};
constexpr float MIX_X = 16.0f, MIX_Y = 64.0f;
constexpr float EN_BTN_Y = 62.5f;
constexpr float EN_BTN_X[3] = {35.0f, 49.5f, 64.0f};
constexpr float EN_LED_DX = -6.6f;
constexpr float J[5] = {10.0f, 23.3f, 36.6f, 49.9f, 63.2f};
constexpr float R1 = 82.0f, R2 = 95.0f, R3 = 108.0f;
}
