// Generated by gen_maelstrom.py — do not edit by hand.
#pragma once

namespace mslayout {
constexpr float YA = 15.0f;
constexpr float LEVEL_X = 10.0f, MIXK_X = 26.0f, MIXCV_X = 41.0f;
constexpr float LED_X = 52.0f, LED_Y = 12.0f;
constexpr float YB = 33.5f;
constexpr float PITCH_X = 17.0f, ECHO_X = 44.0f;
constexpr float YC = 56.5f;
constexpr float DEPTH_X = 10.0f, FB_X = 30.5f, FRZ_X = 51.0f;
constexpr float YD = 72.2f;
constexpr float TRIM_X[4] = {10.0f, 23.6f, 37.2f, 50.8f};
constexpr float R1 = 84.0f, R2 = 98.0f, R3 = 113.0f;
constexpr float JC[4] = {10.0f, 23.6f, 37.2f, 50.8f};
}
