// Generated by gen_abacus.py — do not edit by hand.
#pragma once

namespace alayout {
constexpr float TOP_Y = 13.0f;
constexpr float IN1_X = 9.0f, TRIG1_X = 21.5f, IN2_X = 38.0f, IN3_X = 63.6f;
constexpr float TRIG4_X = 80.1f, IN4_X = 92.6f;
constexpr float CYC_BTN_X = 11.5f, CYC_BTN_Y = 26.5f;
constexpr float CYC_LED_X = 18.5f, CYC_LED_Y = 22.0f;
constexpr float RISE_X = 31.5f, RISE_Y = 30.0f;
constexpr float FALL_X = 31.5f, FALL_Y = 52.0f;
constexpr float RESP_X = 29.0f, RESP_Y = 72.0f;
constexpr float ATT_X = 50.8f;
constexpr float ATT_Y[4] = {21.0f, 37.0f, 53.0f, 69.0f};
constexpr float CH2LED_X = 43.6f, CH2LED_Y = 37.0f;
constexpr float CH3LED_X = 43.6f, CH3LED_Y = 53.0f;
constexpr float EDGE_X = 9.0f;
constexpr float EDGE_Y[4] = {37.0f, 48.0f, 59.0f, 70.5f};
constexpr float VAR_Y = 90.0f;
constexpr float VAR_X[4] = {33.5f, 45.0f, 56.6f, 68.1f};
constexpr float BUS_Y = 104.0f;
constexpr float BUS_X[3] = {39.3f, 50.8f, 62.3f};
constexpr float ORLED_X = 31.0f, ORLED_Y = 104.0f;
constexpr float INVLED_X = 70.6f, INVLED_Y = 104.0f;
constexpr float CORNER_Y = 117.0f;
constexpr float EOR_X = 9.0f, U1_X = 21.5f, U4_X = 80.1f, EOC_X = 92.6f;
constexpr float CH1LED_X = 9.0f, CH1LED_Y = 101.0f;
constexpr float CH4LED_X = 92.6f, CH4LED_Y = 101.0f;
constexpr float EORLED_X = 21.5f, EORLED_Y = 101.0f;
constexpr float EOCLED_X = 80.1f, EOCLED_Y = 101.0f;
constexpr float W_MM = 101.6f;
}
