// Generated by gen_capo.py — do not edit by hand.
#pragma once

namespace pl {
constexpr float QLED_Y = 13.0f, QLED_X0 = 11.0f, QLED_DX = 8.2f;
constexpr float BANK_X = 12.0f, BANK_Y = 27.0f;
constexpr float WAVE_X = 12.0f, WAVE_Y = 43.0f;
constexpr float FREQ_X = 36.5f, FREQ_Y = 28.0f;
constexpr float FINE_X = 36.5f, FINE_Y = 44.5f;
constexpr float QUAL_X = 59.0f, QUAL_Y = 45.0f;
constexpr float BTN_X = 63.0f, BTN_LED_DX = -6.8f;
constexpr float MODE_Y = 21.5f, HARM_Y = 29.0f, TRIAD_Y = 36.5f;
constexpr float FM_JACK_X = 9.0f, FM_ROW_Y = 64.0f, FM_ATT_X = 20.5f;
constexpr float VOICING_X = 40.0f, VOICING_Y = 58.5f;
constexpr float CV_Y = 78.0f;
constexpr float CV_X[6] = {9.0f, 19.6f, 30.2f, 40.8f, 51.4f, 62.0f};
constexpr float OUT_Y = 96.0f;
constexpr float OUT_X[5] = {11.0f, 23.2f, 35.4f, 47.6f, 59.8f};
}
